---
title: "BG_Assignment1_Part1_SnowshoeHare"
author: "Bridget Gibbons"
date: "1/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
# Load packages

library(tidyverse)
library(janitor)
library(kableExtra)
library(lubridate)

```

```{r}
# Read in the data, retain columns for grid, sex, and weight. 
# Correct case differences in columns
# Retain only the hares with fully identified sex information (m or f, no ?)
# Remove NA values

hares <- read_csv("showshoe_lter.csv") %>% 
  mutate(date = mdy(date)) %>% 
  separate(date, into = c("year", "month", "day", sep = "-")) %>% 
  select(year, grid, sex, weight, hindft) %>% 
  mutate(grid = str_to_lower(grid),
         sex = str_to_lower(sex)) %>% 
  filter(
    sex == "m" | sex == "f"
  ) %>% 
  filter(
    year == "2008" | year == "2009" | year == "2010" | year == "2011" | year == "2012"
  )


hares_nona <- hares %>% 
  drop_na()

```

```{r, include = FALSE}
# Create summary table, grouped by the grid and sex. Report the number of hare observations and the average weight for each group

hare_table <- hares_nona %>% 
  group_by(year, grid, sex) %>% 
  summarize(
    count = length(sex),
    avg_weight = round(mean(weight), digits = 0),
    avg_hindft = round(mean(hindft), digits = 0)
  )

hare_table

```

```{r}

# Make the table look nice

kable(hare_table, col.names = c("Year", "Grid Name","Sex","Hare Count", "Average Weight", "Average Hind Foot Size"), align = "c", caption = "Table 1. Snowshoe Hare Statistics for Two Grid Locations from 2008 to 2012 ") %>% 
  add_header_above(c("", "Snowshoe Hare Statistics" = 4, "")) %>% 
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left") %>% 
  footnote(symbol = c("Data Source: "))


```


```{r}

hares_plot <- ggplot(hare_table, aes(x = year, y = count, group = sex)) +
  geom_line(aes(color = sex)) +
  geom_point(aes(color = sex, size = avg_hindft)) +
  facet_wrap(~ grid) +
  theme_minimal() +
  labs(x = "Count", y = "Year")

hares_plot
```

```{r}



```

